variables:
  BUILD_VERSION: 1.0.20
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:${BUILD_VERSION}
  DOCKER_DEV_IMAGE_TAG: monfex/simple-trading-web-terminal:dev
  K8S_DEV_APP_SELECTOR: simple-trading-web-terminal
  K8S_DEV_NAMESPACE: simple-trading-dev
  K8S_DEV_CONTEXT: SimpleTradingDevKubernetes
  BUILD_FOLDER: wwwroot
  KUBERNETES_APP_SELECTOR_NAME: simple-trading-web-terminal

stages:
  - build
  - build-test
  - publish-dev
  - publish
  - publish-k8s-dev
  - publish-kubernetes-dev
  - publish-kubernetes-test

build:
  stage: build
  image: node:14.6.0
  script:
    - pwd
    - ls -la
    - npm -v
    - node -v
    - npm i
    - npm run build
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - development

build-test:
  stage: build-test
  image: node:14.6.0
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - test

publish:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - test

publish-dev:
  stage: publish-dev
  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG}
  image: docker:latest
  only:
    - development


publish-kubernetes-dev:
  stage: publish-kubernetes-dev
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_DEV_CONTEXT
  script:
    - kubectl delete pods -l app=${KUBERNETES_APP_SELECTOR_NAME} --namespace=$KUBERNETES_DEV_NAMESPACE
  only:
    - development

publish-kubernetes-test:
  stage: publish-kubernetes-test
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_DEV_CONTEXT
  script:
    - kubectl delete pods -l app=${KUBERNETES_APP_SELECTOR_NAME} --namespace=$KUBERNETES_DEV_NAMESPACE
    - kubectl set image deployments/${KUBERNETES_APP_SELECTOR_NAME} ${KUBERNETES_APP_SELECTOR_NAME}=$DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} --namespace=$KUBERNETES_DEV_NAMESPACE
    - kubectl patch deployment ${KUBERNETES_APP_SELECTOR_NAME} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --namespace=$KUBERNETES_DEV_NAMESPACE
  only:
    - test
