variables:
  DOCKER_IMAGE_TAG: monfex/simple-trading-web-terminal:1.0.2
  DOCKER_DEV_IMAGE_TAG: monfex/simple-trading-web-terminal:dev
  K8S_DEV_APP_SELECTOR: simple-trading-web-terminal
  K8S_DEV_NAMESPACE: simple-trading-dev
  K8S_DEV_CONTEXT: SimpleTradingDevKubernetes
  BUILD_FOLDER: wwwroot
  KUBERNETES_APP_SELECTOR_NAME: simple-trading-web-terminal

stages:
  - publish-dev
  - publish
  - publish-k8s-dev
  - publish-kubernetes-dev
  - publish-kubernetes-test

publish:
  stage: publish
  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - apt install nodejs
    - apt install npm
    - npm i
    - npm run build
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}
  image: docker:latest
  only:
    - test

publish-dev:
  stage: publish-dev
#  tags: [monfex]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - npm i
    - npm run build
    - ls ${BUILD_FOLDER}
    - ls
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build -t $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG}
  image: docker:latest
  only:
    - development


publish-kubernetes-dev:
  stage: publish-kubernetes-dev
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_DEV_CONTEXT
  script:
    - kubectl delete pods -l app=${KUBERNETES_APP_SELECTOR_NAME} --namespace=$KUBERNETES_DEV_NAMESPACE
  only:
    - development

publish-kubernetes-test:
  stage: publish-kubernetes-test
  image: simpletrading.azurecr.io/monfex/simple-trading-kubectl:latest
  services:
    - docker:dind
  before_script:
    - kubectl config use-context $KUBERNETES_DEV_CONTEXT
  script:
    - kubectl delete pods -l app=${KUBERNETES_APP_SELECTOR_NAME} --namespace=$KUBERNETES_DEV_NAMESPACE
    - kubectl set image deployments/${KUBERNETES_APP_SELECTOR_NAME} ${KUBERNETES_APP_SELECTOR_NAME}=$DOCKER_REGISTRY_HOST/${DOCKER_DEV_IMAGE_TAG} --namespace=$KUBERNETES_DEV_NAMESPACE
    - kubectl patch deployment ${KUBERNETES_APP_SELECTOR_NAME} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --namespace=$KUBERNETES_DEV_NAMESPACE
  only:
    - test
