name: Release App
on:
  push:
    tags: "*.*.*"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set env var
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF_NAME,,})" >> $GITHUB_ENV
        echo "IMAGE=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "DATE=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date --utc +%F.%H%M%S)" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -v
#       run: |
#         npm -v
#         node -v
#         pwd
#         ls -la

    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run buildProd

#     - name: Npm build
#       run: npm run buildProd

    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ./
        repository: my-cfd-platform/${{ env.IMAGE }}
        tags: ${{ env.BRANCH }}
        build_args: BUILD_VERSION=${{ env.BRANCH }}
